### ISSUE TITLE
Loading Pipeline from GitHub

### ISSUE THREAD

**Issue by mdorkhah** [GateNLP/gateplugin-Python#63] opened 2021-04-07 18:29 UTC
Trying to load pipeline from GitHub, got the following error:
gs_app = GateWorkerAnnotator(pipeline="https://github.com/gogsbread/ResumeParser/blob/master/GATEFiles/ANNIEResumeParser.gapp", gatehome="C:/Program Files/GATE_Developer_9.0.1", port=25334)

Trying to start GATE Worker on port=25334 host=127.0.0.1 log=false keep=false
PythonWorkerRunner.java: starting server with 25334/127.0.0.1/JLm7xbXFURfE0ZerqG7WCdBymv8/false
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-191-71f936516f45> in <module>
----> 1 gs_app = GateWorkerAnnotator(pipeline="https://github.com/gogsbread/ResumeParser/blob/master/GATEFiles/ANNIEResumeParser.gapp", gatehome="C:/Program Files/GATE_Developer_9.0.1", port=25334)

~\miniconda3\lib\site-packages\gatenlp\gateworker.py in __init__(self, pipeline, gatehome, port, annsets_send, annsets_receive, replace_anns)
   1028         self.replace_anns = replace_anns
   1029         self.gs = GateWorker(port=port, start=True, gatehome=gatehome)
-> 1030         self.controller = self.gs.worker.loadPipelineFromFile(self.pipeline)
   1031         self.corpus = self.gs.worker.newCorpus()
   1032         self.controller.setCorpus(self.corpus)

~\miniconda3\lib\site-packages\py4j\java_gateway.py in __call__(self, *args)
   1307 
   1308         answer = self.gateway_client.send_command(command)
-> 1309         return_value = get_return_value(
   1310             answer, self.gateway_client, self.target_id, self.name)
   1311 

~\miniconda3\lib\site-packages\py4j\protocol.py in get_return_value(answer, gateway_client, target_id, name)
    324             value = OUTPUT_CONVERTER[type](answer[2:], gateway_client)
    325             if answer[1] == REFERENCE_TYPE:
--> 326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
    328                     format(target_id, ".", name), value)

Py4JJavaError: An error occurred while calling t.loadPipelineFromFile.
: gate.util.GateRuntimeException: Could not load pipeline from https://github.com/gogsbread/ResumeParser/blob/master/GATEFiles/ANNIEResumeParser.gapp
	at gate.plugin.python.PythonWorker.loadPipelineFromFile(PythonWorker.java:128)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.FileNotFoundException: C:\Users\moham\Desktop\ResumeParser\https:\github.com\gogsbread\ResumeParser\blob\master\GATEFiles\ANNIEResumeParser.gapp (The filename, directory name, or volume label syntax is incorrect)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at sun.net.www.protocol.file.FileURLConnection.connect(Unknown Source)
	at sun.net.www.protocol.file.FileURLConnection.getInputStream(Unknown Source)
	at java.net.URL.openStream(Unknown Source)
	at gate.util.persistence.PersistenceManager.isXmlApplicationFile(PersistenceManager.java:1350)
	at gate.util.persistence.PersistenceManager.loadObjectFromUri(PersistenceManager.java:1194)
	at gate.util.persistence.PersistenceManager.loadObjectFromFile(PersistenceManager.java:1154)
	at gate.plugin.python.PythonWorker.loadPipelineFromFile(PythonWorker.java:126)
	... 11 more

**Comment by johann-petrak** [comment] 2021-04-07 21:40
It is not possible to directly load a pipeline from a HTTP/HTTPS URL, this is a limitation of GATE and not related to gatenlp or the GateWorker or the Python plugin. 

The proper way to load the pipeline would be to first clone the repository to your local disk and then load the pipeline from within the repository directory.

However, the pipeline in that repository is very old and will not work with GATE 8.6.1 GATE 9.0.1, that pipeline would need to get.

In general, if you want to use pipelines with the GateWorker from Python, please test the pipeline first from within Java GATE.
The Python GateWorker is essentially Python code that "remote-controls" Java GATE and is able to exchange documents and results from Python to Java and back.

**Comment by johann-petrak** [comment] 2021-04-07 21:40
Closing as this is not a bug.

**Closed by johann-petrak** 2021-04-07 21:40 UTC

**Comment by greenwoodma** [comment] 2021-04-08 07:33
> It is not possible to directly load a pipeline from a HTTP/HTTPS URL, this is a limitation of GATE and not related to gatenlp or the GateWorker or the Python plugin.

I'm a bit confused by this statement. However you load a pipeline it eventually ends up going through `gate.util.persistence.PersistenceManager.loadObjectFromUri(URI uri)`. From the GUI that happens by getting a `File` instance from the file chooser and then calling `File.toURI()` or if you are loading a pre-packaged pipeline then it comes from `ResourceReference.toURI()`, but nothing is stopping you from calling the method using a URL and calling `URL.toURI()` to get the URI. In fact loading an app from within a maven based plugin does so via a URL, albeit it a `jar://` not `http://`.

In this case I'm sure you are right and the underlying problem is the application requiring a valid GATE_HOME which is no longer supported, but you can use the groovy console to see that trying to load it is at least possible

![image](https://user-images.githubusercontent.com/3025272/113985819-7569d400-9844-11eb-8919-fcdc869339b7.png)

and in fact if I try it with an app that will load into 9.0 you can see that it does work as expected

![image](https://user-images.githubusercontent.com/3025272/113986023-b06c0780-9844-11eb-8c50-7462299fb925.png)

although note that in both cases I used the raw github URL and not the one from the original bug report. Either way this suggests to me that the pipeline loading code here is assuming that pipelines can only ever be loaded from a file which isn't technically correct. Not sure if that counts as a bug or not, hence I'm going to hit "comment" rather than "reopen and comment" and leave that decision to you.

**Comment by johann-petrak** [comment] 2021-04-08 08:41
Ah ok, thanks for clearing this up, Mark! 

I quickly tested this in the GATE GUI yesterday and and it failed, but it turns out, I tested it in the wrong way and I jumped to conclusions.

I have now created #64 for this. 

@mdorkhah, please excuse the incorrect info and confusion!
